### ISSUE TITLE
Sometimes doesn't automatically pick a criteria

### ISSUE THREAD

**Issue by glandium** [mozilla/cargo-vet#183] opened 2022-06-14 22:37 UTC
When running `cargo vet certify`, sometimes it picks a criteria on its own, sometimes not. Example of case where it doesn't: unicode-ident:1.0.0 -> 1.0.1 in m-c.

**Comment by Gankra** [comment] 2022-06-14 22:51
Could you describe/reproduce the series of commands you performed? We try to guess based on previous commands, which we dump in `/tmp/cargo-vet-checkout/command-history.json` (or whatever your platform specific tempdir is).

In particular we harvest the criteria from either an existing unaudited entry when doing a full audit for that version (not applicable) or from a previous vet-suggest. If you were just doing that certify from the knowledge that you were updating the deps, it wouldn't have the suggest to source from. Bobby did want to just uncondtionally do a suggest internally but I'm a bit resistant to that since there's ~3 different kinds of "suggests" and it's very expensive to run any of them, so it's not clear which one to use.

**Comment by glandium** [comment] 2022-06-14 22:57
unicode-ident 1.0.0 has an unaudited entry and I ran `diff unicode-ident 1.0.0 1.0.1` before `certify`

**Comment by glandium** [comment] 2022-06-14 22:59
I didn't run `suggest` for it, though, which might be the cause.

**Comment by glandium** [comment] 2022-06-14 23:00
> `/tmp/cargo-vet-checkout/command-history.json`

Sounds like this should be in `~/.cache` or something.

**Comment by mystor** [comment] 2022-06-14 23:04
> > `/tmp/cargo-vet-checkout/command-history.json`
> 
> Sounds like this should be in `~/.cache` or something.

Yeah, cargo-vet currently caches in a temporary directory, it definitely might be worth using a XDG cache directory on linux. I've filed #184 for that.

**Comment by bholley** [comment] 2022-06-15 19:16
Either #191 or #192 will fix this, and we're doing both.

**Comment by bholley** [comment] 2022-06-15 19:45
Closing this in favor of those two issues.

**Closed by bholley** 2022-06-15 19:45 UTC
